export const coursePayments = [
  {
    id:"1",
    userId: "1",
    courses: [
      { courseId: "1" },
      { courseId: "2" },
      { courseId: "3" },
      { courseId: "4" },
    ],
    price: 230,
    transactionId: "7843628372",
    bankType: "Commercial Bank of Ethiopia(CBE)",
    status: false,
  },
  { id:"2",
    userId: "2",
    courses: [
      { courseId: "2" },
      { courseId: "3" },
      { courseId: "5" },
    ],
    price: 150,
    transactionId: "9347568271",
    bankType: "National Bank of Ethiopia(NBE)",
    status: true,
  },
  {
    id:"3",
    userId: "3",
    courses: [
      { courseId: "1" },
      { courseId: "4" },
    ],
    price: 120,
    transactionId: "6438927510",
    bankType: "Awash Bank",
    status: true,
  },
  {

    id:"4",
    userId: "4",
    courses: [
      { courseId: "3" },
      { courseId: "5" },
    ],
    price: 180,
    transactionId: "5729364812",
    bankType: "Dashen Bank",
    status: false,
  },
  { id:"5",
    userId: "5",
    courses: [
      { courseId: "1" },
      { courseId: "2" },
      { courseId: "4" },
      { courseId: "5" },
    ],
    price: 280,
    transactionId: "8123456790",
    bankType: "United Bank",
    status: true,
  },
];
